/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './app/__root'
import { Route as publicIndexImport } from './app/(public)/index'
import { Route as RoleLayoutImport } from './app/$role/_layout'
import { Route as authRecoverPasswordIndexImport } from './app/(auth)/recover-password/index'
import { Route as authLoginIndexImport } from './app/(auth)/login/index'

// Create Virtual Routes

const RoleImport = createFileRoute('/$role')()
const RoleLayoutEmployeesIndexLazyImport = createFileRoute(
  '/$role/_layout/employees/',
)()
const RoleLayoutDashboardIndexLazyImport = createFileRoute(
  '/$role/_layout/dashboard/',
)()

// Create/Update Routes

const RoleRoute = RoleImport.update({
  path: '/$role',
  getParentRoute: () => rootRoute,
} as any)

const publicIndexRoute = publicIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RoleLayoutRoute = RoleLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => RoleRoute,
} as any)

const authRecoverPasswordIndexRoute = authRecoverPasswordIndexImport.update({
  path: '/recover-password/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginIndexRoute = authLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const RoleLayoutEmployeesIndexLazyRoute =
  RoleLayoutEmployeesIndexLazyImport.update({
    path: '/employees/',
    getParentRoute: () => RoleLayoutRoute,
  } as any).lazy(() =>
    import('./app/$role/_layout.employees/index.lazy').then((d) => d.Route),
  )

const RoleLayoutDashboardIndexLazyRoute =
  RoleLayoutDashboardIndexLazyImport.update({
    path: '/dashboard/',
    getParentRoute: () => RoleLayoutRoute,
  } as any).lazy(() =>
    import('./app/$role/_layout.dashboard/index.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$role': {
      preLoaderRoute: typeof RoleImport
      parentRoute: typeof rootRoute
    }
    '/$role/_layout': {
      preLoaderRoute: typeof RoleLayoutImport
      parentRoute: typeof RoleRoute
    }
    '/(public)/': {
      preLoaderRoute: typeof publicIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login/': {
      preLoaderRoute: typeof authLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/recover-password/': {
      preLoaderRoute: typeof authRecoverPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/$role/_layout/dashboard/': {
      preLoaderRoute: typeof RoleLayoutDashboardIndexLazyImport
      parentRoute: typeof RoleLayoutImport
    }
    '/$role/_layout/employees/': {
      preLoaderRoute: typeof RoleLayoutEmployeesIndexLazyImport
      parentRoute: typeof RoleLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  RoleRoute.addChildren([
    RoleLayoutRoute.addChildren([
      RoleLayoutDashboardIndexLazyRoute,
      RoleLayoutEmployeesIndexLazyRoute,
    ]),
  ]),
  publicIndexRoute,
  authLoginIndexRoute,
  authRecoverPasswordIndexRoute,
])

/* prettier-ignore-end */
